#############################################################################
# Makefile for building: kyna
# Generated by qmake (2.01a) (Qt 4.3.2) on: Sa Feb 2 16:02:44 2008
# Project:  kyna.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile kyna.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SHARED -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = helper.cpp \
		kynabomb.cpp \
		kynabuff.cpp \
		kynacontrol.cpp \
		kynaexit.cpp \
		kynafield.cpp \
		kynagoodie.cpp \
		kynaitem.cpp \
		kynaki.cpp \
		kynalevel.cpp \
		kynapixmapitem.cpp \
		kynaplayer.cpp \
		kynasettingsreader.cpp \
		kynatileset.cpp \
		kynaunit.cpp \
		kynawindow.cpp \
		main.cpp \
		kynatimer.cpp moc_kynabomb.cpp \
		moc_kynabuff.cpp \
		moc_kynacontrol.cpp \
		moc_kynafield.cpp \
		moc_kynaki.cpp \
		moc_kynalevel.cpp \
		moc_kynapixmapitem.cpp \
		moc_kynaplayer.cpp \
		moc_kynaunit.cpp \
		moc_kynawindow.cpp \
		moc_kynatimer.cpp
OBJECTS       = helper.o \
		kynabomb.o \
		kynabuff.o \
		kynacontrol.o \
		kynaexit.o \
		kynafield.o \
		kynagoodie.o \
		kynaitem.o \
		kynaki.o \
		kynalevel.o \
		kynapixmapitem.o \
		kynaplayer.o \
		kynasettingsreader.o \
		kynatileset.o \
		kynaunit.o \
		kynawindow.o \
		main.o \
		kynatimer.o \
		moc_kynabomb.o \
		moc_kynabuff.o \
		moc_kynacontrol.o \
		moc_kynafield.o \
		moc_kynaki.o \
		moc_kynalevel.o \
		moc_kynapixmapitem.o \
		moc_kynaplayer.o \
		moc_kynaunit.o \
		moc_kynawindow.o \
		moc_kynatimer.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		kyna.pro
QMAKE_TARGET  = kyna
DESTDIR       = 
TARGET        = kyna

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kyna.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile kyna.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile kyna.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/kyna1.0.0 || $(MKDIR) .tmp/kyna1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/kyna1.0.0/ && $(COPY_FILE) --parents defines.h helper.h kynabomb.h kynabuff.h kynacontrol.h kynaexit.h kynafield.h kynagoodie.h kynaitem.h kynaki.h kynalevel.h kynapixmapitem.h kynaplayer.h kynasettingsreader.h kynatileset.h kynatypes.h kynaunit.h kynawindow.h kynatimer.h .tmp/kyna1.0.0/ && $(COPY_FILE) --parents helper.cpp kynabomb.cpp kynabuff.cpp kynacontrol.cpp kynaexit.cpp kynafield.cpp kynagoodie.cpp kynaitem.cpp kynaki.cpp kynalevel.cpp kynapixmapitem.cpp kynaplayer.cpp kynasettingsreader.cpp kynatileset.cpp kynaunit.cpp kynawindow.cpp main.cpp kynatimer.cpp .tmp/kyna1.0.0/ && (cd `dirname .tmp/kyna1.0.0` && $(TAR) kyna1.0.0.tar kyna1.0.0 && $(COMPRESS) kyna1.0.0.tar) && $(MOVE) `dirname .tmp/kyna1.0.0`/kyna1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/kyna1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_kynabomb.cpp moc_kynabuff.cpp moc_kynacontrol.cpp moc_kynafield.cpp moc_kynaki.cpp moc_kynalevel.cpp moc_kynapixmapitem.cpp moc_kynaplayer.cpp moc_kynaunit.cpp moc_kynawindow.cpp moc_kynatimer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_kynabomb.cpp moc_kynabuff.cpp moc_kynacontrol.cpp moc_kynafield.cpp moc_kynaki.cpp moc_kynalevel.cpp moc_kynapixmapitem.cpp moc_kynaplayer.cpp moc_kynaunit.cpp moc_kynawindow.cpp moc_kynatimer.cpp
moc_kynabomb.cpp: kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynabomb.h -o moc_kynabomb.cpp

moc_kynabuff.cpp: kynabuff.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynabuff.h -o moc_kynabuff.cpp

moc_kynacontrol.cpp: kynatypes.h \
		kynacontrol.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynacontrol.h -o moc_kynacontrol.cpp

moc_kynafield.cpp: defines.h \
		kynalevel.h \
		kynatimer.h \
		kynatypes.h \
		kynafield.h \
		kynaexit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h \
		kynafield.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynafield.h -o moc_kynafield.cpp

moc_kynaki.cpp: kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaki.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynaki.h -o moc_kynaki.cpp

moc_kynalevel.cpp: defines.h \
		kynatimer.h \
		kynatypes.h \
		kynafield.h \
		kynalevel.h \
		kynaplayer.h \
		kynaunit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaki.h \
		kynagoodie.h \
		kynaexit.h \
		kynalevel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynalevel.h -o moc_kynalevel.cpp

moc_kynapixmapitem.cpp: kynatileset.h \
		defines.h \
		kynapixmapitem.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynapixmapitem.h -o moc_kynapixmapitem.cpp

moc_kynaplayer.cpp: kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaplayer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynaplayer.h -o moc_kynaplayer.cpp

moc_kynaunit.cpp: kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaunit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynaunit.h -o moc_kynaunit.cpp

moc_kynawindow.cpp: kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynalevel.h \
		kynatimer.h \
		kynafield.h \
		kynaexit.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h \
		kynasettingsreader.h \
		kynawindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynawindow.h -o moc_kynawindow.cpp

moc_kynatimer.cpp: kynatimer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) kynatimer.h -o moc_kynatimer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

helper.o: helper.cpp helper.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helper.o helper.cpp

kynabomb.o: kynabomb.cpp kynabomb.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynafield.h \
		kynalevel.h \
		kynatimer.h \
		kynaplayer.h \
		kynaunit.h \
		kynabuff.h \
		kynacontrol.h \
		kynaki.h \
		kynagoodie.h \
		kynaexit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynabomb.o kynabomb.cpp

kynabuff.o: kynabuff.cpp kynabuff.h \
		kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynacontrol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynabuff.o kynabuff.cpp

kynacontrol.o: kynacontrol.cpp kynacontrol.h \
		kynatypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynacontrol.o kynacontrol.cpp

kynaexit.o: kynaexit.cpp kynaexit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynafield.h \
		kynalevel.h \
		kynatimer.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynaexit.o kynaexit.cpp

kynafield.o: kynafield.cpp kynafield.h \
		defines.h \
		kynalevel.h \
		kynatimer.h \
		kynatypes.h \
		kynaplayer.h \
		kynaunit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaki.h \
		kynagoodie.h \
		kynaexit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynafield.o kynafield.cpp

kynagoodie.o: kynagoodie.cpp kynagoodie.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynafield.h \
		kynalevel.h \
		kynatimer.h \
		kynaplayer.h \
		kynaki.h \
		kynaexit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynagoodie.o kynagoodie.cpp

kynaitem.o: kynaitem.cpp kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynaitem.o kynaitem.cpp

kynaki.o: kynaki.cpp kynalevel.h \
		defines.h \
		kynatimer.h \
		kynatypes.h \
		kynafield.h \
		kynaexit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynaki.o kynaki.cpp

kynalevel.o: kynalevel.cpp kynalevel.h \
		defines.h \
		kynatimer.h \
		kynatypes.h \
		kynafield.h \
		kynaexit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h \
		kynawindow.h \
		kynasettingsreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynalevel.o kynalevel.cpp

kynapixmapitem.o: kynapixmapitem.cpp kynapixmapitem.h \
		kynatileset.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynapixmapitem.o kynapixmapitem.cpp

kynaplayer.o: kynaplayer.cpp kynalevel.h \
		defines.h \
		kynatimer.h \
		kynatypes.h \
		kynafield.h \
		kynaexit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynaplayer.o kynaplayer.cpp

kynasettingsreader.o: kynasettingsreader.cpp kynasettingsreader.h \
		kynatypes.h \
		kynalevel.h \
		defines.h \
		kynatimer.h \
		kynafield.h \
		kynaexit.h \
		kynaitem.h \
		kynapixmapitem.h \
		kynatileset.h \
		helper.h \
		kynaunit.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynasettingsreader.o kynasettingsreader.cpp

kynatileset.o: kynatileset.cpp kynatileset.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynatileset.o kynatileset.cpp

kynaunit.o: kynaunit.cpp kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynalevel.h \
		kynatimer.h \
		kynafield.h \
		kynaexit.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynaunit.o kynaunit.cpp

kynawindow.o: kynawindow.cpp kynawindow.h \
		kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynalevel.h \
		kynatimer.h \
		kynafield.h \
		kynaexit.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h \
		kynasettingsreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynawindow.o kynawindow.cpp

main.o: main.cpp kynawindow.h \
		kynaunit.h \
		kynaitem.h \
		defines.h \
		kynapixmapitem.h \
		kynatileset.h \
		kynatypes.h \
		helper.h \
		kynabomb.h \
		kynabuff.h \
		kynacontrol.h \
		kynalevel.h \
		kynatimer.h \
		kynafield.h \
		kynaexit.h \
		kynaplayer.h \
		kynaki.h \
		kynagoodie.h \
		kynasettingsreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

kynatimer.o: kynatimer.cpp kynatimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kynatimer.o kynatimer.cpp

moc_kynabomb.o: moc_kynabomb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynabomb.o moc_kynabomb.cpp

moc_kynabuff.o: moc_kynabuff.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynabuff.o moc_kynabuff.cpp

moc_kynacontrol.o: moc_kynacontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynacontrol.o moc_kynacontrol.cpp

moc_kynafield.o: moc_kynafield.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynafield.o moc_kynafield.cpp

moc_kynaki.o: moc_kynaki.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynaki.o moc_kynaki.cpp

moc_kynalevel.o: moc_kynalevel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynalevel.o moc_kynalevel.cpp

moc_kynapixmapitem.o: moc_kynapixmapitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynapixmapitem.o moc_kynapixmapitem.cpp

moc_kynaplayer.o: moc_kynaplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynaplayer.o moc_kynaplayer.cpp

moc_kynaunit.o: moc_kynaunit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynaunit.o moc_kynaunit.cpp

moc_kynawindow.o: moc_kynawindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynawindow.o moc_kynawindow.cpp

moc_kynatimer.o: moc_kynatimer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kynatimer.o moc_kynatimer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

